### PR TITLE
Prevent gpsd events to be issued 2 times

### PR DESCRIPTION
**Pull request by Tarrask**

### CODE REVIEW

**Comment by Tarrask** [comment]
Ok, I hope that I made this pull request correctly ...

**Comment by eelcocramer** [comment]
It looks great :+1: 

I just have to find the time to test before merging it... 😅

**Comment by eelcocramer** [comment]
Merged and published to npm as version 0.2.4

Thank you for contributing!

**Comment by Tarrask** [comment]
You're welcome,
I'm glad to be able to contribute to open source software :)

**Pull request merged**
